--CREATE TABLE [dbo].[Customers] (
--    [Id]          INT IDENTITY(1,1) ,
--    [FirstName]   VARCHAR(50) NULL,
--    [LastName]    VARCHAR(50) NULL,
--    [Email]       VARCHAR(50) NULL,
--    [DateOfBirth] DATETIME NULL
--);

-- Insert sample data into the Customers table
--INSERT INTO [dbo].[Customers] ([FirstName], [LastName], [Email], [DateOfBirth])
--VALUES
--    ('John', 'Doe', 'john.doe@example.com', '1990-05-15'),
--    ('Jane', 'Smith', 'jane.smith@example.com', '1985-10-20'),
--    ('Alice', 'Johnson', 'alice.johnson@example.com', '1978-03-25'),
--    ('Bob', 'Brown', 'bob.brown@example.com', '1995-12-10');
